# Services for Unraid Management Agent integration

# Docker Container Services
container_start:
  name: Start Container
  description: Start a Docker container
  fields:
    container_id:
      name: Container ID
      description: The ID or name of the container to start
      required: true
      example: "nginx"
      selector:
        text:

container_stop:
  name: Stop Container
  description: Stop a Docker container
  fields:
    container_id:
      name: Container ID
      description: The ID or name of the container to stop
      required: true
      example: "nginx"
      selector:
        text:

container_restart:
  name: Restart Container
  description: Restart a Docker container
  fields:
    container_id:
      name: Container ID
      description: The ID or name of the container to restart
      required: true
      example: "nginx"
      selector:
        text:

container_pause:
  name: Pause Container
  description: Pause a running Docker container
  fields:
    container_id:
      name: Container ID
      description: The ID or name of the container to pause
      required: true
      example: "nginx"
      selector:
        text:

container_resume:
  name: Resume Container
  description: Resume a paused Docker container (unpause)
  fields:
    container_id:
      name: Container ID
      description: The ID or name of the container to resume
      required: true
      example: "nginx"
      selector:
        text:

# Virtual Machine Services
vm_start:
  name: Start VM
  description: Start a virtual machine
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to start
      required: true
      example: "Ubuntu"
      selector:
        text:

vm_stop:
  name: Stop VM
  description: Stop a virtual machine (graceful shutdown)
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to stop
      required: true
      example: "Ubuntu"
      selector:
        text:

vm_restart:
  name: Restart VM
  description: Restart a virtual machine
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to restart
      required: true
      example: "Ubuntu"
      selector:
        text:

vm_pause:
  name: Pause VM
  description: Pause a running virtual machine (suspend to RAM)
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to pause
      required: true
      example: "Ubuntu"
      selector:
        text:

vm_resume:
  name: Resume VM
  description: Resume a paused virtual machine
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to resume
      required: true
      example: "Ubuntu"
      selector:
        text:

vm_hibernate:
  name: Hibernate VM
  description: Hibernate a virtual machine (suspend to disk)
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to hibernate
      required: true
      example: "Ubuntu"
      selector:
        text:

vm_force_stop:
  name: Force Stop VM
  description: Force stop a virtual machine (equivalent to power off)
  fields:
    vm_id:
      name: VM ID
      description: The ID or name of the VM to force stop
      required: true
      example: "Ubuntu"
      selector:
        text:

# Array Control Services
array_start:
  name: Start Array
  description: Start the Unraid array

array_stop:
  name: Stop Array
  description: Stop the Unraid array

# Parity Check Services
parity_check_start:
  name: Start Parity Check
  description: Start a parity check

parity_check_stop:
  name: Stop Parity Check
  description: Stop the running parity check

parity_check_pause:
  name: Pause Parity Check
  description: Pause the running parity check

parity_check_resume:
  name: Resume Parity Check
  description: Resume a paused parity check

